### ISSUE TITLE
How to implement Stardust into a TypeScript-only project?

### ISSUE THREAD

**Issue by nextlevelshit** [stardustjs/stardust#1]
```ts
import * as Stardust from 'stardust-core';
import { WebGLPlatform, WebGLCanvasPlatform2D } from 'stardust-webgl';
```

This would be my attempt to include the basic classes from stardust. Now I would like to create a platform:

```ts
const canvasEl = document.createElement('canvas');
const platform = Stardust.platform('webgl-2d', canvasEl, 100, 100);
```

Finally, I am running into this error:

> ERROR TypeError: Cannot read property 'apply' of undefined
> at Function.push../node_modules/stardust-core/dist/platform/index.js.Platform.Create (index.js:72)
> at Object.platform (index.js:82)

I've already tried to back-trace that error, but because of the missing documentation and TS-only examples I did not get so far. I'd appreciate any help.

**Comment by donghaoren** [comment]
It seems when we

```typescript
import { WebGLPlatform, WebGLCanvasPlatform2D } from 'stardust-webgl';
```

TypeScript doesn't actually `require('stardust-webgl')`. Below is what's in the TypeScript compiled js code:

```javascript
"use strict";
exports.__esModule = true;
var Stardust = require("stardust-core");
var canvasEl = document.createElement('canvas');
var platform = Stardust.platform('webgl-2d', canvasEl, 100, 100);
```

As you can see, it's not mentioning `stardust-webgl` at all. The issue arises because the `stardust-webgl` module is what registering these platform types (in this case, `webgl-2d`): https://github.com/stardustjs/stardust/blob/dev/packages/stardust-webgl/src/stardust-webgl.ts

To solve this issue, you can just use:

```typescript
import 'stardust-webgl'; // This will make typescript require("stardust-webgl");
```

Or, if you prefer the original import statement, you can create the platform by:

```typescript
const platform = new WebGLCanvasPlatform2D(canvasEl, 100, 100);
```

Initially I wanted to separate core and webgl, but it seems this is creating unnecessary complications, perhaps it's a good idea, as you said in the email, to unify them into a single package (e.g., `stardustjs`) now.

**Comment by nextlevelshit** [comment]
After that migration maybe I will better understand stardust. As soon as I've got the code running, I will put some spare time into the project. First, I will try your proposal, thanks.

```ts

import * as Stardust from 'stardust-core'; // for e.g. creating and manipulating marks
import { WebGLCanvasPlatform2D } from 'stardust-webgl'; // for webgl canvas usage
 
// ...

const canvasEl = document.createElement('canvas');
const platform = new WebGLCanvasPlatform2D(canvasEl, 100, 100);
```
Solved the issue.
